### ISSUE TITLE
Metrics stack

### ISSUE THREAD

**Issue by lmeyerov** [TheDataRideAlongs/ProjectDomino#45]
docker-compose
Prometheus 
Neo4j -> Prometheus
Prefect -> slack fails
Docs ??

**Comment by bechbd** [comment]
Neo4j-> Prometheus is done http://grafana.projectdomino.org/

**Comment by lmeyerov** [comment]
![image](https://user-images.githubusercontent.com/4249447/78854151-7370f900-79d5-11ea-8d6f-023b45d62d4d.png)


Super cool!
